export const propsList = [
  "previousScale",
  "scale",
  "positionX",
  "positionY",
  "sensitivity",
  "maxScale",
  "minScale",
  "scaleAnimationPadding",
  "wheelAnimationSpeed",
  "zoomInAnimationSpeed",
  "zoomOutAnimationSpeed",
  "pinchAnimationSpeed",
  "panAnimationSpeed",
  "resetAnimationSpeed",
  "paddingAnimationSpeed",
  "minPositionX",
  "minPositionY",
  "maxPositionX",
  "maxPositionY",
  "limitToBounds",
  "zoomingEnabled",
  "panningEnabled",
  "transformEnabled",
  "pinchEnabled",
  "limitToWrapperBounds",
  "disabled",
  "zoomOutStep",
  "zoomInStep",
  "dbClickStep",
  "pinchSensitivity",
  "dbClickEnabled",
  "lastPositionZoomEnabled",
  "enableZoomThrottling",
  "onWheelStart",
  "onWheel",
  "onWheelStop",
  "onPanningStart",
  "onPanning",
  "onPanningStop",
  "onPinchingStart",
  "onPinching",
  "onPinchingStop",
  "onZoomChange",
  "defaultPositionX",
  "defaultPositionY",
  "defaultScale",
  "lockAxisX",
  "lockAxisY",
  "velocityTimeBasedOnMove",
  "velocitySensitivity",
  "isCentered",
  "enableWheel",
  "enableTouchPadPinch",
  "enableVelocity",
  "limitToWrapperOnWheel",
];

export const getValidPropsFromObject = props => {
  return Object.keys(props).reduce((acc, key) => {
    if (propsList.includes(key)) {
      acc[key] = props[key];
    }
    return acc;
  }, {});
};
