name: "Build Docs"

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook docs
        run: yarn build-docs
