name: "Deploy Storybook Documentation"

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn build-docs

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4.3.3
          branch: gh-pages
          folder: storybook-static
